name: agrimix
description: AgriMix App (Flutter + Firebase + Provider)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  uuid: ^4.5.1
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  fl_chart: ^0.69.0
  path: ^1.9.0

  # Firebase
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.2

  # Notifications
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  http: ^1.2.2
  
  # Logging
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true